### ISSUE TITLE
Python 3.10 fails to start Heralding with errors

### ISSUE THREAD

**Issue by t3chn0m4g3** [johnnykv/heralding#150]
Heralding has issues with Python 3.10 with regard to imap and fails to start with the following error:
```
heralding    | 2022-06-02 14:58:25,244 (heralding.honeypot) Could not start Imap server on port 143. Error: BaseEventLoop.create_server() got an unexpected keyword argument 'loop'
heralding    | 2022-06-02 14:58:25,244 (root) BaseEventLoop.create_server() got an unexpected keyword argument 'loop'
heralding    | Traceback (most recent call last):
heralding    |   File "/usr/bin/heralding", line 163, in <module>
heralding    |     honeypot.start()
heralding    |   File "/usr/lib/python3.10/site-packages/heralding/honeypot.py", line 196, in start
heralding    |     raise ex
heralding    |   File "/usr/lib/python3.10/site-packages/heralding/honeypot.py", line 188, in start
heralding    |     server = self.loop.run_until_complete(server_coro)
heralding    |   File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
heralding    |     return future.result()
heralding    |   File "/usr/lib/python3.10/asyncio/streams.py", line 84, in start_server
heralding    |     return await loop.create_server(factory, host, port, **kwds)
heralding    | TypeError: BaseEventLoop.create_server() got an unexpected keyword argument 'loop'
heralding    | Traceback (most recent call last):
heralding    |   File "/usr/bin/heralding", line 163, in <module>
heralding    |     honeypot.start()
heralding    |   File "/usr/lib/python3.10/site-packages/heralding/honeypot.py", line 196, in start
heralding    |     raise ex
heralding    |   File "/usr/lib/python3.10/site-packages/heralding/honeypot.py", line 188, in start
heralding    |     server = self.loop.run_until_complete(server_coro)
heralding    |   File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
heralding    |     return future.result()
heralding    |   File "/usr/lib/python3.10/asyncio/streams.py", line 84, in start_server
heralding    |     return await loop.create_server(factory, host, port, **kwds)
heralding    | TypeError: BaseEventLoop.create_server() got an unexpected keyword argument 'loop'
heralding    |
heralding    | During handling of the above exception, another exception occurred:
heralding    |
heralding    | Traceback (most recent call last):
heralding    |   File "/usr/bin/heralding", line 166, in <module>
heralding    |     honeypot.stop()
heralding    |   File "/usr/lib/python3.10/site-packages/heralding/honeypot.py", line 216, in stop
heralding    |     self.loop.run_until_complete(common.cancel_all_pending_tasks(self.loop))
heralding    |   File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
heralding    |     return future.result()
heralding    |   File "/usr/lib/python3.10/site-packages/heralding/misc/common.py", line 45, in cancel_all_pending_tasks
heralding    |     await asyncio.wait_for(task, timeout=5, loop=loop)
heralding    | TypeError: wait_for() got an unexpected keyword argument 'loop'
```
Python 3.9 runs without any issues.

**Comment by kajojify** [comment]
Hello @t3chn0m4g3! Thank you for your report! 
The problem is _loop_ parameter was removed for many asyncio functions starting from Python 3.10 as well as for `asyncio.wait_for` - https://docs.python.org/3/library/asyncio-task.html?highlight=wait_for#asyncio.wait_for
I think we need to make some adjustments.

**Comment by t3chn0m4g3** [comment]
@kajojify Thanks for the swift reply. If you need help with testing please ping me.

**Comment by t3chn0m4g3** [comment]
@kajojify Have you had the chance yet to take a closer look?

**Comment by dpeldo** [comment]
I just ran into this as well on a fresh Ubuntu 22.04 install. Looks like running 3.9 is still the solution for now.

**Comment by t3chn0m4g3** [comment]
@johnnykv @kajojify Any updates on this?

**Comment by Symon3** [comment]
Excellent progress, so it runs now, but, and I might be mistaken, I think there are still some problems when the honeypot is triggered.
ssh trigger crashes because of line 173 of honeypot.py
telnet trigger doesn't work, telnetsrvlib.py line 94, 102, 117, 113
smtp trigger needs fixing smtp.py line 223 e.g. 
        loop = asyncio.get_running_loop()
        fqdn = await loop.run_in_executor(None, socket.getfqdn)

If I find anymore I'll post again. Apologies for not doing the commits, not sure I'm good enough at Python for that.

Anyway, I hope it helps.

p.s. To get the new version working, I needed to do this after following the installation instructions because there's not a tag for the new 3.10 compatible version.

cp -R ~/heralding/heralding ~/heralding/heralding-env/lib/python3.11/site-packages/

Is that correct?

**Comment by t3chn0m4g3** [comment]
I cannot reproduce this. Can you provide logs?

**Comment by Symon3** [comment]
Here's an example. If I follow the installation instructions and copy the new files across, I get this error when using ssh from an 'attacker' to trigger the honeypot.

2024-02-19 09:35:17,721 (asyncio) Exception in callback SSHConnection.connection_made(<_SelectorSoc...e, bufsize=0>>)
handle: <Handle SSHConnection.connection_made(<_SelectorSoc...e, bufsize=0>>)>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/administrator/heralding/heralding-env/lib/python3.11/site-packages/asyncssh/connection.py", line 1277, in connection_made
  File "/home/administrator/heralding/heralding-env/lib/python3.11/site-packages/heralding/honeypot.py", line 173, in <lambda>
TypeError: SSH.__init__() takes 2 positional arguments but 3 were given 

I fixed this by changing line 173 of honeypot.py 

lambda: SshClass(ssh_options, self.loop),

by getting rid of the second parameter.

I had similar problems with telnet:-

 2024-02-19 09:36:25,024 (asyncio) Task exception was never retrieved
future: <Task finished name='Task-35' coro=<HandlerBase.handle_session() done, defined at /home/administrator/heralding/heralding-env/lib/python3.11/site-packages/heralding/capabilities/handlerbase.py:71> exception=TypeError("TelnetHandlerBase.__init__() missing 1 required positional argument: 'loop'")>
Traceback (most recent call last):
  File "/home/administrator/heralding/heralding-env/lib/python3.11/site-packages/heralding/capabilities/handlerbase.py", line 83, in handle_session
  File "/usr/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/home/administrator/heralding/heralding-env/lib/python3.11/site-packages/heralding/capabilities/telnet.py", line 34, in execute_capability
  File "/home/administrator/heralding/heralding-env/lib/python3.11/site-packages/heralding/capabilities/telnet.py", line 54, in __init__
TypeError: TelnetHandlerBase.__init__() missing 1 required positional argument: 'loop'

smtp:-

2024-02-19 10:26:47,961 (asyncio) Task exception was never retrieved
future: <Task finished name='Task-34' coro=<HandlerBase.handle_session() done, defined at /home/administrator/heralding/heralding-env/lib/python3.11/site-packages/heralding/capabilities/handlerbase.py:71> exception=AttributeError("'smtp' object has no attribute 'loop'")>
Traceback (most recent call last):
  File "/home/administrator/heralding/heralding-env/lib/python3.11/site-packages/heralding/capabilities/handlerbase.py", line 83, in handle_session
  File "/usr/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/home/administrator/heralding/heralding-env/lib/python3.11/site-packages/heralding/capabilities/smtp.py", line 213, in execute_capability
  File "/home/administrator/heralding/heralding-env/lib/python3.11/site-packages/heralding/capabilities/smtp.py", line 223, in setfqdn
AttributeError: 'smtp' object has no attribute 'loop'

**Comment by t3chn0m4g3** [comment]
Ahh, thanks, that helps. Will have a look at it.

**Comment by Symon3** [comment]
Thanks very much.

**Comment by t3chn0m4g3** [comment]
@Symon3 @johnnykv This is (hopefully) and finally fixed with #157 
However, unrelated I noticed TLS errors which are probably a regression from #135 
```
heralding  | 2024-02-28 17:26:35,188 (asyncio) Unhandled exception in client_connected_cb
heralding  | transport: <_SelectorSocketTransport closed fd=35>
heralding  | Traceback (most recent call last):
heralding  |   File "/usr/lib/python3.11/site-packages/heralding/capabilities/handlerbase.py", line 83, in handle_session
heralding  |     await asyncio.wait_for(
heralding  |   File "/usr/lib/python3.11/asyncio/tasks.py", line 489, in wait_for
heralding  |     return fut.result()
heralding  |            ^^^^^^^^^^^^
heralding  |   File "/usr/lib/python3.11/site-packages/heralding/capabilities/rdp.py", line 57, in execute_capability
heralding  |     await self._handle_session(reader, writer, session)
heralding  |   File "/usr/lib/python3.11/site-packages/heralding/capabilities/rdp.py", line 87, in _handle_session
heralding  |     await tls_obj.do_tls_handshake()
heralding  |   File "/usr/lib/python3.11/site-packages/heralding/libs/msrdp/tls.py", line 66, in do_tls_handshake
heralding  |     self._tlsObj.do_handshake()
heralding  |   File "/usr/lib/python3.11/ssl.py", line 979, in do_handshake
heralding  |     self._sslobj.do_handshake()
heralding  | ssl.SSLSyscallError: Some I/O error occurred (_ssl.c:1006)
```
